// <auto-generated />
namespace ApplicationCrud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Dados5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dados5));
        
        string IMigrationMetadata.Id
        {
            get { return "201710311747176_Dados5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
